/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package yuzen

import kotlin.test.Test
import kotlin.test.assertTrue
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.assertThrows
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe
import java.io.*

object LibraryTest: Spek({
  describe("test") {
    it("test") {
      assertTrue(true === true)
    }
  }
})
